### ISSUE TITLE
Replaced config interfaces: Inserted command no power inline supply enable gives CLI error

### ISSUE THREAD

**Issue by pascal71** [pascal71/community.tplink#1]
The following config -> state: replaced gives a CLI error for unsupported switch command:

```
 - name: Configure interfaces (method2)
    become: yes
    community.tplink.ios_interfaces:
      config:
      - name: gigabitEthernet 1/0/1
        duplex: auto
        speed: auto
      - name: gigabitEthernet 1/0/2
        duplex: auto
        speed: auto
      - name: gigabitEthernet 1/0/8
        description: "The 8th intf"
        duplex: auto
        speed: 1000
        eee: enabled
        poe: disabled
        flow-control: enabled
      state: replaced
```

_T1500G-10PSN06(config-if)#ng task execution. To see the full traceback, use -vvv. The error was: 
fatal: [switch6]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/pascal/.ansible/tmp/ansible-local-99747uwjh0ctt/ansible-tmp-1641022084.6619582-99827-155970667307031/AnsiballZ_ios_interfaces.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/pascal/.ansible/tmp/ansible-local-99747uwjh0ctt/ansible-tmp-1641022084.6619582-99827-155970667307031/AnsiballZ_ios_interfaces.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/pascal/.ansible/tmp/ansible-local-99747uwjh0ctt/ansible-tmp-1641022084.6619582-99827-155970667307031/AnsiballZ_ios_interfaces.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.tplink.plugins.modules.ios_interfaces', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_community.tplink.ios_interfaces_payload_vDC0DX/ansible_community.tplink.ios_interfaces_payload.zip/ansible_collections/community/tplink/plugins/modules/ios_interfaces.py\", line 568, in <module>\n  File \"/tmp/ansible_community.tplink.ios_interfaces_payload_vDC0DX/ansible_community.tplink.ios_interfaces_payload.zip/ansible_collections/community/tplink/plugins/modules/ios_interfaces.py\", line 563, in main\n  File \"/tmp/ansible_community.tplink.ios_interfaces_payload_vDC0DX/ansible_community.tplink.ios_interfaces_payload.zip/ansible_collections/community/tplink/plugins/module_utils/network/ios/config/interfaces/interfaces.py\", line 98, in execute_module\n  File \"/tmp/ansible_community.tplink.ios_interfaces_payload_vDC0DX/ansible_community.tplink.ios_interfaces_payload.zip/ansible/module_utils/connection.py\", line 195, in __rpc__\nansible.module_utils.connection.ConnectionError: no power inline supply enable\r\n#2022-01-01 08:28:08,[Link]/5/Gi1/0/1 changed state to down.\r\n\r\n\u001b[16C\u001b[1A------------------------------------------^\r\nError: Invalid parameter. \r\n\r\n\rT1500G-10PSN06(config-if)#\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}_
